[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$htBaS4kRAoAQYixFCOH83w$q4Fb/dZQVeVvyqgyVBxGC8GFl77hKchnViuEf.FBrkg3C/QDUnxKqJLHdVDxyJlg2EeAOQaihNBlnHwZquqmjA
db_host = postgres
db_port = 5432
db_user = odoo
db_password = odoo
http_port = 8069
logfile = /var/log/odoo/odoo.log
log_level = info

