#!/usr/bin/env python3
"""
Email Handler Skill
Processes emails and creates appropriate responses
"""
import sys
import json
from pathlib import Path
from datetime import datetime


def process_emails(vault_path: str, action: str = 'analyze'):
    """
    Process emails in the vault

    Args:
        vault_path: Path to the Obsidian vault
        action: Action to perform (analyze, draft_reply, mark_done)
    """
    vault = Path(vault_path)
    needs_action = vault / 'Needs_Action'
    pending_approval = vault / 'Pending_Approval'
    done_dir = vault / 'Done'

    # Ensure directories exist
    for dir in [needs_action, pending_approval, done_dir]:
        dir.mkdir(parents=True, exist_ok=True)

    results = {
        'emails_found': 0,
        'replies_drafted': 0,
        'emails_processed': []
    }

    # Find email tasks
    email_files = [f for f in needs_action.glob('EMAIL_*.md')]
    results['emails_found'] = len(email_files)

    if action == 'analyze':
        for email_file in email_files:
            analysis = analyze_email(email_file)
            results['emails_processed'].append(analysis)

    elif action == 'draft_reply':
        for email_file in email_files[:3]:  # Process first 3
            reply_file = draft_reply(email_file, pending_approval)
            if reply_file:
                results['replies_drafted'] += 1
                results['emails_processed'].append(email_file.name)

    return results


def analyze_email(email_file: Path) -> dict:
    """
    Analyze an email and determine priority/action needed

    Args:
        email_file: Path to email file

    Returns:
        Analysis results
    """
    try:
        content = email_file.read_text(encoding='utf-8')

        # Extract metadata
        metadata = {}
        for line in content.split('\n'):
            if line.startswith('from:'):
                metadata['from'] = line.split('from:')[1].strip()
            elif line.startswith('subject:'):
                metadata['subject'] = line.split('subject:')[1].strip()
            elif line.startswith('priority:'):
                metadata['priority'] = line.split('priority:')[1].strip()

        # Determine action needed
        action_needed = determine_action(content, metadata)

        return {
            'file': email_file.name,
            'from': metadata.get('from', 'Unknown'),
            'subject': metadata.get('subject', 'No Subject'),
            'priority': metadata.get('priority', 'normal'),
            'action_needed': action_needed
        }

    except Exception as e:
        return {
            'file': email_file.name,
            'error': str(e)
        }


def determine_action(content: str, metadata: dict) -> str:
    """Determine what action is needed for an email"""
    content_lower = content.lower()

    # Check for urgent keywords
    if any(word in content_lower for word in ['urgent', 'asap', 'emergency']):
        return 'immediate_reply'

    # Check for questions
    if '?' in content:
        return 'reply_needed'

    # Check for FYI/informational
    if any(word in content_lower for word in ['fyi', 'for your information', 'update']):
        return 'acknowledge'

    return 'review'


def draft_reply(email_file: Path, pending_approval: Path) -> Path:
    """
    Draft a reply to an email

    Args:
        email_file: Path to email file
        pending_approval: Directory for approval requests

    Returns:
        Path to draft reply file
    """
    try:
        content = email_file.read_text(encoding='utf-8')

        # Extract email details
        sender = 'Unknown'
        subject = 'No Subject'
        for line in content.split('\n'):
            if line.startswith('from:'):
                sender = line.split('from:')[1].strip()
            elif line.startswith('subject:'):
                subject = line.split('subject:')[1].strip()

        # Generate reply
        reply_body = generate_reply(content, sender, subject)

        # Create draft file
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        draft_filename = f'REPLY_{timestamp}_{email_file.stem}.md'
        draft_filepath = pending_approval / draft_filename

        draft_content = f"""---
type: email
action: reply
original_file: {email_file.name}
to: {sender}
subject: Re: {subject}
created: {datetime.now().isoformat()}
status: pending_approval
priority: normal
---

# Email Reply - Approval Required

## Original Email
From: {sender}
Subject: {subject}

## Proposed Reply

{reply_body}

## Instructions
**To approve and send:** Move this file to `/Approved` folder
**To reject:** Move this file to `/Rejected` folder
**To edit:** Modify the reply above, then move to `/Approved`

---
*Generated by Email Handler Skill at {datetime.now().isoformat()}*
"""

        draft_filepath.write_text(draft_content, encoding='utf-8')
        return draft_filepath

    except Exception as e:
        print(f"Error drafting reply: {e}", file=sys.stderr)
        return None


def generate_reply(original_content: str, sender: str, subject: str) -> str:
    """
    Generate a reply based on email content

    In production, this would use Claude API for intelligent responses.
    For this hackathon, we'll use templates.
    """
    content_lower = original_content.lower()

    # Extract sender name
    sender_name = sender.split('@')[0].split('<')[-1].strip()

    # Determine reply type
    if 'meeting' in content_lower or 'schedule' in content_lower:
        return f"""Hi {sender_name},

Thank you for reaching out regarding the meeting.

I'd be happy to discuss this further. Could you please share your availability for next week? I'm generally available Tuesday through Thursday, 10 AM - 4 PM.

Looking forward to connecting.

Best regards"""

    elif '?' in original_content:
        return f"""Hi {sender_name},

Thank you for your email.

I've reviewed your question and will get back to you with a detailed response by end of day tomorrow.

In the meantime, if you need immediate assistance, please don't hesitate to reach out.

Best regards"""

    else:
        return f"""Hi {sender_name},

Thank you for your email regarding {subject}.

I've received your message and will review it carefully. I'll follow up with you shortly.

Best regards"""


def main():
    """Main entry point"""
    if len(sys.argv) < 2:
        print("Usage: python email_handler.py <vault_path> [action]", file=sys.stderr)
        print("Actions: analyze, draft_reply", file=sys.stderr)
        sys.exit(1)

    vault_path = sys.argv[1]
    action = sys.argv[2] if len(sys.argv) > 2 else 'analyze'

    print(f"Processing emails in vault: {vault_path}")
    print(f"Action: {action}")

    results = process_emails(vault_path, action)

    print(f"\nResults:")
    print(f"  Emails found: {results['emails_found']}")
    print(f"  Replies drafted: {results['replies_drafted']}")

    if results['emails_processed']:
        print(f"\nProcessed:")
        for item in results['emails_processed']:
            if isinstance(item, dict):
                print(f"  - {item.get('file', 'unknown')}: {item.get('action_needed', 'N/A')}")
            else:
                print(f"  - {item}")

    # Output JSON for programmatic use
    print(f"\n{json.dumps(results)}")


if __name__ == '__main__':
    main()
