#!/usr/bin/env python3
"""
Process Vault Tasks Skill
Processes tasks from the AI Employee vault and creates action plans
"""
import sys
import json
from pathlib import Path
from datetime import datetime


def process_vault_tasks(vault_path: str):
    """
    Process tasks in the vault

    Args:
        vault_path: Path to the Obsidian vault
    """
    vault = Path(vault_path)
    inbox = vault / 'Inbox'
    needs_action = vault / 'Needs_Action'
    plans_dir = vault / 'Plans'
    done_dir = vault / 'Done'

    # Ensure directories exist
    for dir in [inbox, needs_action, plans_dir, done_dir]:
        dir.mkdir(parents=True, exist_ok=True)

    results = {
        'inbox_items': 0,
        'needs_action_items': 0,
        'plans_created': 0,
        'items_processed': []
    }

    # Process Inbox items
    inbox_files = list(inbox.glob('*.md'))
    results['inbox_items'] = len(inbox_files)

    # Process Needs_Action items
    needs_action_files = list(needs_action.glob('*.md'))
    results['needs_action_items'] = len(needs_action_files)

    # Create plans for complex tasks
    for task_file in needs_action_files[:3]:  # Process first 3
        plan_file = create_plan(task_file, plans_dir)
        if plan_file:
            results['plans_created'] += 1
            results['items_processed'].append(task_file.name)

    # Update dashboard
    update_dashboard(vault, results)

    return results


def create_plan(task_file: Path, plans_dir: Path) -> Path:
    """
    Create a Plan.md file for a task

    Args:
        task_file: Path to task file
        plans_dir: Directory for plans

    Returns:
        Path to created plan file
    """
    try:
        content = task_file.read_text(encoding='utf-8')

        # Extract task details
        task_type = 'unknown'
        for line in content.split('\n'):
            if line.startswith('type:'):
                task_type = line.split('type:')[1].strip()
                break

        # Create plan filename
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        plan_filename = f'PLAN_{timestamp}_{task_file.stem}.md'
        plan_filepath = plans_dir / plan_filename

        # Create plan content
        plan_content = f"""---
type: action_plan
source_task: {task_file.name}
created: {datetime.now().isoformat()}
status: pending
---

# Action Plan: {task_file.stem}

## Task Summary
Source: {task_file.name}
Type: {task_type}

## Analysis
This task requires structured planning and execution.

## Execution Steps

### Step 1: Analyze Requirements
- [ ] Review task details
- [ ] Identify dependencies
- [ ] Determine priority

### Step 2: Gather Information
- [ ] Collect necessary data
- [ ] Review relevant documentation
- [ ] Identify stakeholders

### Step 3: Execute
- [ ] Implement solution
- [ ] Test thoroughly
- [ ] Document results

### Step 4: Complete
- [ ] Verify completion
- [ ] Update stakeholders
- [ ] Move to Done folder

## Notes
Plan automatically generated by process-vault-tasks skill.
Customize steps as needed for specific task requirements.

---
*Generated at {datetime.now().isoformat()}*
"""

        plan_filepath.write_text(plan_content, encoding='utf-8')
        return plan_filepath

    except Exception as e:
        print(f"Error creating plan: {e}", file=sys.stderr)
        return None


def update_dashboard(vault: Path, results: dict):
    """
    Update Dashboard.md with current status

    Args:
        vault: Path to vault
        results: Processing results
    """
    dashboard = vault / 'Dashboard.md'

    if not dashboard.exists():
        return

    try:
        content = dashboard.read_text(encoding='utf-8')

        # Update recent activity section
        activity_update = f"""
### Recent Activity
- Emails monitored: 0
- WhatsApp messages: 0
- LinkedIn posts: 0
- Tasks in Inbox: {results['inbox_items']}
- Tasks in Needs_Action: {results['needs_action_items']}
- Plans created: {results['plans_created']}
- Last processed: {datetime.now().strftime('%Y-%m-%d %H:%M')}
"""

        # Simple replacement (in production, use proper markdown parsing)
        if '### Recent Activity' in content:
            parts = content.split('### Recent Activity')
            before = parts[0]
            after_parts = parts[1].split('##', 1)
            after = '##' + after_parts[1] if len(after_parts) > 1 else ''

            new_content = before + activity_update + '\n' + after
            dashboard.write_text(new_content, encoding='utf-8')

    except Exception as e:
        print(f"Error updating dashboard: {e}", file=sys.stderr)


def main():
    """Main entry point"""
    if len(sys.argv) < 2:
        print("Usage: python process_vault_tasks.py <vault_path>", file=sys.stderr)
        sys.exit(1)

    vault_path = sys.argv[1]

    print(f"Processing vault tasks at: {vault_path}")
    results = process_vault_tasks(vault_path)

    print(f"\nResults:")
    print(f"  Inbox items: {results['inbox_items']}")
    print(f"  Needs Action items: {results['needs_action_items']}")
    print(f"  Plans created: {results['plans_created']}")

    if results['items_processed']:
        print(f"\nProcessed:")
        for item in results['items_processed']:
            print(f"  - {item}")

    # Output JSON for programmatic use
    print(f"\n{json.dumps(results)}")


if __name__ == '__main__':
    main()
