"""
File System Watcher
Monitors the Inbox folder for new files and creates action items
"""
from pathlib import Path
from datetime import datetime
import shutil
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler
from base_watcher import BaseWatcher


class InboxHandler(FileSystemEventHandler):
    """Handler for file system events in the Inbox folder"""

    def __init__(self, watcher):
        self.watcher = watcher
        self.processed_files = set()

    def on_created(self, event):
        """Handle file creation events"""
        if event.is_directory:
            return

        source = Path(event.src_path)

        # Avoid processing the same file multiple times
        if source in self.processed_files:
            return

        self.processed_files.add(source)
        self.watcher.logger.info(f'New file detected: {source.name}')

        # Create action file
        self.watcher.create_action_file(source)


class FileSystemWatcher(BaseWatcher):
    """Watches the Inbox folder for new files"""

    def __init__(self, vault_path: str):
        super().__init__(vault_path, check_interval=5)
        self.inbox = self.vault_path / 'Inbox'
        self.inbox.mkdir(parents=True, exist_ok=True)
        self.observer = None

    def check_for_updates(self) -> list:
        """
        Check for existing files in Inbox (for initial scan)

        Returns:
            List of files in Inbox
        """
        files = list(self.inbox.glob('*'))
        # Filter out directories and hidden files
        return [f for f in files if f.is_file() and not f.name.startswith('.')]

    def create_action_file(self, source_file: Path) -> Path:
        """
        Create an action file in Needs_Action folder

        Args:
            source_file: Path to the source file

        Returns:
            Path to the created action file
        """
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        action_filename = f'FILE_{timestamp}_{source_file.name}.md'
        action_filepath = self.needs_action / action_filename

        # Get file metadata
        file_size = source_file.stat().st_size
        file_type = source_file.suffix
        created_time = datetime.fromtimestamp(source_file.stat().st_ctime)

        # Create markdown content
        content = f"""---
type: file_drop
original_name: {source_file.name}
file_type: {file_type}
size_bytes: {file_size}
detected: {datetime.now().isoformat()}
created: {created_time.isoformat()}
priority: normal
status: pending
---

# New File Dropped for Processing

## File Details
- **Original Name**: {source_file.name}
- **File Type**: {file_type}
- **Size**: {file_size} bytes ({file_size / 1024:.2f} KB)
- **Location**: {source_file}

## Suggested Actions
- [ ] Review file contents
- [ ] Determine appropriate action
- [ ] Process according to Company Handbook rules
- [ ] Move to /Done when complete

## Notes
File automatically detected by File System Watcher.
Awaiting Claude Code processing.

---
*Generated by FileSystemWatcher at {datetime.now().isoformat()}*
"""

        # Write the action file
        action_filepath.write_text(content, encoding='utf-8')

        self.logger.info(f'Created action file: {action_filepath.name}')

        # Log to vault logs
        self._log_action(source_file, action_filepath)

        return action_filepath

    def _log_action(self, source_file: Path, action_file: Path):
        """Log the action to the vault logs"""
        log_dir = self.vault_path / 'Logs'
        log_dir.mkdir(parents=True, exist_ok=True)

        today = datetime.now().strftime('%Y-%m-%d')
        log_file = log_dir / f'{today}.log'

        log_entry = f"[{datetime.now().isoformat()}] FILE_DETECTED: {source_file.name} -> {action_file.name}\n"

        with open(log_file, 'a', encoding='utf-8') as f:
            f.write(log_entry)

    def run(self):
        """Start the file system watcher with real-time monitoring"""
        self.logger.info(f'Starting FileSystemWatcher')
        self.logger.info(f'Monitoring inbox: {self.inbox}')

        # Process any existing files first
        existing_files = self.check_for_updates()
        if existing_files:
            self.logger.info(f'Processing {len(existing_files)} existing files')
            for file in existing_files:
                self.create_action_file(file)

        # Set up real-time monitoring
        event_handler = InboxHandler(self)
        self.observer = Observer()
        self.observer.schedule(event_handler, str(self.inbox), recursive=False)
        self.observer.start()

        self.logger.info('Real-time monitoring started. Press Ctrl+C to stop.')

        try:
            while True:
                import time
                time.sleep(1)
        except KeyboardInterrupt:
            self.logger.info('Stopping watcher...')
            self.observer.stop()

        self.observer.join()
        self.logger.info('Watcher stopped')


if __name__ == '__main__':
    # Get vault path from command line or use default
    import sys

    if len(sys.argv) > 1:
        vault_path = sys.argv[1]
    else:
        # Default to the AI_Employee_Vault in the current directory structure
        vault_path = Path(__file__).parent.parent / 'AI_Employee_Vault'

    watcher = FileSystemWatcher(str(vault_path))
    watcher.run()
