#!/usr/bin/env python3
"""
LinkedIn Poster Skill
Generates and schedules LinkedIn posts
"""
import sys
import json
from pathlib import Path
from datetime import datetime, timedelta


def generate_weekly_posts(vault_path: str):
    """
    Generate a week's worth of LinkedIn posts

    Args:
        vault_path: Path to the Obsidian vault
    """
    vault = Path(vault_path)
    posts_dir = vault / 'LinkedIn_Posts'
    scheduled_dir = posts_dir / 'Scheduled'

    # Ensure directories exist
    scheduled_dir.mkdir(parents=True, exist_ok=True)

    # Content topics
    topics = [
        "AI automation",
        "Business efficiency",
        "Productivity tips",
        "Tech trends",
        "Case studies"
    ]

    post_types = ['insight', 'tip', 'question']
    posts_created = []

    # Generate 5 posts
    for i in range(5):
        topic = topics[i % len(topics)]
        post_type = post_types[i % len(post_types)]

        content = generate_post_content(topic, post_type)
        scheduled_time = get_next_posting_slot(i)

        post_file = create_scheduled_post(scheduled_dir, content, scheduled_time)
        posts_created.append({
            'file': post_file.name,
            'topic': topic,
            'scheduled_for': scheduled_time.isoformat()
        })

    return {
        'posts_created': len(posts_created),
        'posts': posts_created
    }


def generate_post_content(topic: str, post_type: str) -> str:
    """Generate LinkedIn post content"""

    templates = {
        'insight': f"""🚀 The Future of {topic}

After working with dozens of businesses, I've noticed a clear trend: {topic} is transforming how we work.

Key takeaways:
• Start small with pilot projects
• Measure everything and iterate
• Focus on ROI, not just features

What's your experience with this? Share in the comments!

#AI #Automation #BusinessGrowth #Productivity #TechInnovation""",

        'tip': f"""💡 Pro Tip: Boost Your {topic} Strategy

Here's a simple framework I use:

1. Identify repetitive tasks
2. Automate the low-hanging fruit
3. Measure time saved
4. Reinvest in high-value work

This approach has saved my clients 20+ hours per week.

Try this today and let me know how it works!

#AI #Automation #BusinessGrowth #Productivity""",

        'question': f"""🤔 Question for my network:

How are you leveraging {topic} in your business?

I'm curious to hear different perspectives. Some swear by full automation, others prefer a hybrid approach.

Drop your thoughts in the comments! 👇

#AI #Automation #BusinessGrowth #Productivity"""
    }

    return templates.get(post_type, templates['insight'])


def get_next_posting_slot(offset: int = 0) -> datetime:
    """Get the next available posting time"""
    # Optimal posting days: Tuesday, Wednesday, Thursday
    # Optimal times: 9 AM, 11 AM

    now = datetime.now()
    target_days = [1, 2, 3]  # Tue, Wed, Thu

    days_ahead = 0
    slots_checked = 0

    while slots_checked <= offset:
        check_date = now + timedelta(days=days_ahead)
        if check_date.weekday() in target_days:
            slots_checked += 1
            if slots_checked > offset:
                return check_date.replace(hour=9, minute=0, second=0, microsecond=0)
        days_ahead += 1

    return now + timedelta(days=1)


def create_scheduled_post(scheduled_dir: Path, content: str, scheduled_time: datetime) -> Path:
    """Create a scheduled post file"""
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    filename = f'POST_{timestamp}.md'
    filepath = scheduled_dir / filename

    post_data = f"""---
type: linkedin_post
created: {datetime.now().isoformat()}
scheduled_for: {scheduled_time.isoformat()}
status: scheduled
approval_required: false
---

# LinkedIn Post - Scheduled

## Scheduled Time
{scheduled_time.strftime('%Y-%m-%d %H:%M')}

## Content
{content}

## Actions
- [ ] Review content
- [ ] Approve for posting
- [ ] Track engagement after posting

---
*Generated by LinkedIn Poster Skill at {datetime.now().isoformat()}*
"""

    filepath.write_text(post_data, encoding='utf-8')
    return filepath


def main():
    """Main entry point"""
    if len(sys.argv) < 2:
        print("Usage: python linkedin_poster.py <vault_path>", file=sys.stderr)
        sys.exit(1)

    vault_path = sys.argv[1]

    print(f"Generating LinkedIn posts for vault: {vault_path}")
    results = generate_weekly_posts(vault_path)

    print(f"\nGenerated {results['posts_created']} posts:")
    for post in results['posts']:
        print(f"  - {post['file']} (Topic: {post['topic']})")
        print(f"    Scheduled for: {post['scheduled_for']}")

    # Output JSON for programmatic use
    print(f"\n{json.dumps(results)}")


if __name__ == '__main__':
    main()
